<html>
<head>
<title>Penguin Voting Booth</title>
</head>
<body>
<h1>Please Vote</h1>
<?php

//defines the 4 variables needed to create a database link
$host = "localhost";
$username = "democracy";
$password = "landslide";
$database = "votes";

//creates a link to the MySQL database through the mysqli_connect command
//mysqli_connect command needs the four inputs of the host, username, password, and database name
$link = mysqli_connect($host, $username, $password, $database);

//creates an if isset that looks for a vote of favorite penguin species
if (isset($_GET['species'])) {

	//variable species that is set to the global variable species
	$species = $_GET['species'];

	//MySQL query that adds the vote cast in the form into the species_id column in the Votes_cast table
	$addquery = "INSERT INTO Votes_cast (species_id) VALUES ('$species')";

	//runs the query against the database
	mysqli_query($link, $addquery);

	//prints the current results of the voting
	print "<p>Thanks for voting!</p>";
	print "<p>Votes so far:</p>";

	//MySQL SELECT statement that selects the species name and counts the votes per species
	//and redefines the counted votes under the new callable of votes
	//creates the relationships between the Species and Votes_cast table using the species_id
	//orders the species by the number of votes from largest to smallest (DESC)
	$votequery = "SELECT Species.name, COUNT(Votes_cast.species_id) AS votes
		FROM Species, Votes_cast
		WHERE Species.species_id = Votes_cast.species_id
 		GROUP BY Species.species_id
		ORDER BY votes DESC";

	//runs the query against the database
	$vote_result = mysqli_query($link, $votequery);

	//creates a while statement where the variable row is set to the array generated by the MySQL query
	while ($row = mysqli_fetch_array($vote_result)) {

		//prints the result of the voting in the format penguin species name =  number of votes
		print "$row[name] = $row[votes] <br />";
	}

	//if there has not been a species submitted this will take effect as the else clause to the if isset
} else {

		//prints the beginning of the drop down selection form and defines the global variable species
   print "<p> Choose your favorite penguin:</p>";
   print "<form method='GET' action='voter.php'><select name='species'>";

	//creates the query to select everything from the tables Species and runs that query against the database
   $listresult = mysqli_query($link, "SELECT * FROM Species");

	//creates a while statement where the variable row is set to the array generated by the MySQL query
   while($row = mysqli_fetch_array($listresult)) {

	//fills in the drop down option as the value = the species_id and the species name as displayed
	//in the drop down these are poppulated from the array
	print "<option value='$row[species_id]'>$row[name]</option>";
   }

		//completes the form creation and creates the submit button
   print "</select>";
   print "<input type='submit' name='submit' value='Submit'></form>";
}

//closes the MySQL link
mysqli_close($link);
?>
</body>
</html>
